### ISSUE TITLE
About Expanded Tree with Corner Link questions

### ISSUE THREAD

**Issue by Xinzheng-Li** [ck-corp/TreePowerBIVisual#1]
Hi,
I use Expanded Tree with Corner Link and try to increase distance between parent node and child node. I tried to modify Distance between nodes, but it just modify distance between up node and down node.
Coule give me some help? 
Thanks.

**Comment by ck-corp** [comment]
@Xinzheng-Li,
**Depth of tree** (under _Tree General_ section) allows you to control the distance between parent and child nodes, whereas **Distance between nodes** (under _Nodes_ section) allows you to specify the distance between sibling nodes.

**Comment by Xinzheng-Li** [comment]
I found it "Depth of tree" !
But can it be adjusted automatically according to the length of the text?
I want to address the problem of overlapping text because it is too long.
Thanks.

**Comment by ck-corp** [comment]
@Xinzheng-Li, that feature is not currently available.

**Comment by Xinzheng-Li** [comment]
OK, thank you again.
